services:
  - type: web
    name: blogify-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate resolve --applied 20251205173512_init && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
